### ISSUE TITLE
Switching tabs after showing omnibox

### ISSUE THREAD

**Issue by james9909** [balzathor/UltimateBrowserProject#47]
Upon hiding the omnibox, then showing it again, switching tabs causes the app to crash. The problem appears to be caused <a href="https://github.com/balzathor/UltimateBrowserProject/blob/38a37d67783bfab598832d7a44b3e47895987614/app/src/main/java/io/github/UltimateBrowserProject/View/SwitcherPanel.java#L370">here</a>.

**Comment by Thunderbottom** [comment]
Was this happening before you changed the code?

**Comment by Thunderbottom** [comment]
Here's the log that you might have gotten -

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.RelativeLayout.getVisibility()' on a null object reference
       at io.github.UltimateBrowserProjectBeta.View.SwitcherPanel.onInterceptTouchEvent()
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2679)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1797)
       at android.app.Activity.dispatchTouchEvent(Activity.java)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2640)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:684)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(<Xposed>)
       at com.android.internal.policy.impl.MultiPhoneWindow$MultiPhoneDecorView.dispatchTouchEvent(MultiPhoneWindow.java:550)
       at android.view.View.dispatchPointerEvent(View.java)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java)
       at android.view.Choreographer.doCallbacks(Choreographer.java)
       at android.view.Choreographer.doFrame(Choreographer.java)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java)
       at android.os.Handler.handleCallback(Handler.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:375)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
```

**Comment by james9909** [comment]
Yes it was happening before I made the previous change.

**Comment by james9909** [comment]
Bug seems to be fixed in <a href="https://github.com/balzathor/UltimateBrowserProject/commit/2d06c5586919911da8688f5c36be3763c2254f32">this</a> commit.

**Comment by Thunderbottom** [comment]
Sorry for replying late, was busy with Uni stuff. 
Must've been something with the Bottom bar scrolling, I need to add comments to every line I suppose.... and possibly better up the code format.

**Comment by james9909** [comment]
Its fine, since I was inactive for a while, which I'm sorry about.

**Comment by Thunderbottom** [comment]
Yeah that's totally fine :)
