### ISSUE TITLE
BUGS LIST - Stack Trace.

### ISSUE THREAD

**Issue by Thunderbottom** [balzathor/UltimateBrowserProject#75]
This issue page will consist of mostly to-fix stack trace for future weekly build updates.

**Comment by Thunderbottom** [comment]
```
Fatal Exception: java.lang.RuntimeException: Unable to pause activity {io.github.UltimateBrowserProject/io.github.UltimateBrowserProject.Activity.BrowserActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String io.github.UltimateBrowserProject.Browser.AlbumController.getUrl()' on a null object reference
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4379)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4338)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4313)
       at android.app.ActivityThread.access$1200(ActivityThread.java:197)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6872)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String io.github.UltimateBrowserProject.Browser.AlbumController.getUrl()' on a null object reference
       at io.github.UltimateBrowserProject.Activity.BrowserActivity.saveOpenTabs(BrowserActivity.java:2539)
       at io.github.UltimateBrowserProject.Activity.BrowserActivity.onPause(BrowserActivity.java:557)
       at android.app.Activity.performPause(Activity.java:6706)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1324)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4365)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4338)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4313)
       at android.app.ActivityThread.access$1200(ActivityThread.java:197)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6872)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by Thunderbottom** [comment]
```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {io.github.UltimateBrowserProject/io.github.UltimateBrowserProject.Activity.HolderActivity}: java.lang.IllegalStateException: Activity {io.github.UltimateBrowserProject/io.github.UltimateBrowserProject.Activity.HolderActivity} did not call finish() prior to onResume() completing
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
Caused by java.lang.IllegalStateException: Activity {io.github.UltimateBrowserProject/io.github.UltimateBrowserProject.Activity.HolderActivity} did not call finish() prior to onResume() completing
       at android.app.Activity.performResume(Activity.java:6339)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
```

**Comment by Thunderbottom** [comment]
People are experiencing blank homescreens even when they have some things pinned to the homepage. We need to fix it soon. I guess it has to do something with restoring tabs...

**Comment by xdevs23** [comment]
It is, when you have multiple tabs open and you switch the tab, it stays blank.

**Comment by xdevs23** [comment]
```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {io.github.UltimateBrowserProject/io.github.UltimateBrowserProject.Activity.HolderActivity}: java.lang.IllegalStateException: Activity {io.github.UltimateBrowserProject/io.github.UltimateBrowserProject.Activity.HolderActivity} did not call finish() prior to onResume() completing
```

This is a main problem we need to fix

**Comment by xdevs23** [comment]
And `ActivityThread.performResumeActivity()`
